import assert from 'node:assert/strict';
import fs from 'node:fs';
import {randomUUID} from 'node:crypto';
import {engine} from './pglite-driver';
import {asOwner,ownerId,db,transaction} from '../lib/postgres';
import {bootstrapWorkspace} from '../lib/bootstrap';
import {getDashboardState,now,recoverInterruptedSessions} from '../lib/db';
import {enqueueResearch,runSlice} from '../lib/jobs';
import {listProvidersPublic,saveProvider,getProviderConfig} from '../lib/providers';
import {searchKnowledge,retrieveMemory} from '../lib/knowledge';
import {resolveApproval} from '../lib/approvals';
import {validateProviderUrl} from '../lib/providerSecurity';
import {commitResearchResult} from '../lib/research';
import {safeAuthDestination,authCallbackUrl} from '../lib/authNavigation';
process.env.DATABASE_URL='postgres://unused';
process.env.ATLAS_MASTER_KEY='a'.repeat(64);
const A=randomUUID(),B=randomUUID();
await engine.exec(`CREATE ROLE authenticated; CREATE ROLE anon; CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY); CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; GRANT USAGE ON SCHEMA auth TO authenticated;`);
await engine.query('INSERT INTO auth.users VALUES($1),($2)',[A,B]);
await engine.exec(fs.readFileSync('supabase/migrations/001_atlas.sql','utf8'));
let checks=0;function ok(name:string){checks++;console.log(`PASS ${name}`);}
for(const input of ['https://evil.example/workspace','//evil.example/workspace','/\\evil.example/workspace','http://[','/auth?mode=update','/api/export'])assert.equal(safeAuthDestination(input),'/workspace');
assert.equal(safeAuthDestination('/workspace?view=history&topic=research'),'/workspace?view=history&topic=research');
assert.equal(safeAuthDestination('/auth?mode=update',true),'/auth?mode=update');
const callback=new URL(authCallbackUrl('https://atlas.example','/workspace?view=history&topic=A&B'));
assert.equal(callback.origin,'https://atlas.example');assert.equal(callback.pathname,'/auth/callback');assert.equal(callback.searchParams.get('next'),'/workspace?view=history&topic=A&B');
assert.equal([...callback.searchParams.keys()].length,1);
ok('Authentication redirects reject external/malformed destinations and preserve workspace context');
const tables=await engine.query(`SELECT c.relname,c.relrowsecurity,c.relforcerowsecurity FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='atlas' AND c.relkind='r'`);
assert.equal(tables.rows.length,19);
for(const t of tables.rows as any[])assert.ok(t.relrowsecurity && t.relforcerowsecurity,`${t.relname} must enforce RLS`);
ok('Every Atlas table, including rate limits and documents, enforces row-level security');
await assert.rejects(()=>db.prepare('SELECT * FROM projects').all(),/Authentication/);ok('Database refuses missing identity');
let projectA:string,sessionA:string,providerA:string;
await asOwner(A,async()=>{
 await bootstrapWorkspace();await bootstrapWorkspace();
 const state=await getDashboardState();assert.equal(state.projects.length,1);projectA=state.projects[0].id;assert.equal(state.sessions.length,0);ok('Idempotent private workspace creation without fake research');
 const job=await enqueueResearch({projectId:projectA,topic:'Ownership controls',instructions:'Keep private'});sessionA=job.sessionId;
 await assert.rejects(()=>enqueueResearch({projectId:projectA,topic:'Duplicate',instructions:''}),/already running/);
 assert.equal(await runSlice(A,job.jobId,job.generation),'queued');
 assert.equal(await runSlice(A,job.jobId,job.generation),'completed');
 assert.equal(await runSlice(A,job.jobId,job.generation),'stopped');
 const done=await getDashboardState();assert.equal(done.findings.length,2);assert.equal(done.clarifications.length,1);assert.equal(done.sessions[0].status,'completed');
 assert.equal((await db.prepare('SELECT * FROM documents').all()).length,3);ok('Queued demo stages, duplicate-start protection, atomic findings and durable documents');
 const approval=done.clarifications[0];await resolveApproval(approval.id,'Governance/Review');
 assert.equal((await getDashboardState()).clarifications.length,0);assert.equal((await retrieveMemory(projectA,'governance','')).decisions.length,1);ok('Human approval updates folders, search, document, and remembered decision');
 assert.ok((await searchKnowledge('ownership')).total>0);assert.equal((await searchKnowledge('nonexistentxyz')).total,0);ok('Postgres ranked search across findings, history, folders and decisions');
 providerA=await saveProvider({presetId:'gemini',name:'Private Gemini',model:'test-model',apiKey:'fixture-secret-only'});
 const list=await listProvidersPublic();assert.equal(list[0].hasKey,true);assert.ok(!JSON.stringify(list).includes('fixture-secret-only'));assert.equal((await getProviderConfig(providerA))!.apiKey,'fixture-secret-only');ok('Encrypted private key round-trip; public provider response has no key');
});
await asOwner(B,async()=>{
 assert.equal((await db.prepare('SELECT * FROM projects').all()).length,0);
 assert.equal((await searchKnowledge('ownership')).total,0);
 assert.equal((await listProvidersPublic()).length,0);
 assert.equal(await getProviderConfig(providerA),null);
 assert.equal((await db.prepare('UPDATE projects SET name=? WHERE id=?').run('attack',projectA)).changes,0);
 await assert.rejects(()=>db.prepare('INSERT INTO projects(owner_id,id,name,topic,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(A,randomUUID(),'forged','forged',now(),now()),/row-level security/);
 await assert.rejects(()=>db.prepare('INSERT INTO folders(id,project_id,path,name,created_at) VALUES(?,?,?,?,?)').run(randomUUID(),projectA,'stolen','stolen',now()),/foreign key/);
 await assert.rejects(()=>enqueueResearch({projectId:projectA,topic:'Unauthorized',instructions:''}),/Project not found/);
 await assert.rejects(()=>resolveApproval(sessionA,'stolen'),/not found/);
 assert.equal((await db.prepare('SELECT * FROM documents').all()).length,0);
 await bootstrapWorkspace();ok('Account B cannot read, search, modify, attach records to, or run Account A research');
});
for(const url of ['http://localhost:11434/v1','https://127.0.0.1/v1','https://169.254.169.254','https://api.openai.com@evil.example/v1','https://api.openai.com/v1?key=foo'])assert.throws(()=>validateProviderUrl(url));validateProviderUrl('https://api.openai.com/v1');ok('Cloud provider endpoint allow-list rejects private and deceptive URLs');
let calls=0,repair=false,pause=false;
globalThis.fetch=async(url:any,init:any)=>{
 assert.ok(String(url).startsWith('https://generativelanguage.googleapis.com/'));calls++;
 const body=JSON.parse(init.body),prompt=body.contents[0].parts[0].text;
 const synthesis=prompt.includes('synthesis and knowledge-organization') || prompt.includes('Repair the following');
 if(pause){pause=false;await db.prepare('UPDATE research_jobs SET pause_requested=1 WHERE status=?').run('running');}
 const payload={executiveSummary:'Auditable result',findings:[{title:'Verified account isolation',summary:'Account isolation tested',content:'Ownership is enforced in the database.',recommendedFolderPath:'Security/Isolation',confidence:.95,tags:['isolation'],sourceUrls:['https://example.org/primary','https://invented.invalid'],rationale:'Security architecture'}],resourcePlacements:[{url:'https://example.org/primary',recommendedFolderPath:'Security/References',confidence:.55,rationale:'Human review required'}],suggestedFolders:[],nextTasks:['Review source'],limitations:[]};
 const text=synthesis?(repair && !prompt.includes('Repair the following')?'invalid json':JSON.stringify(payload)):'Evidence brief with primary source';
 return new Response(JSON.stringify({candidates:[{content:{parts:[{text}]},groundingMetadata:synthesis?{}:{groundingChunks:[{web:{uri:'https://example.org/primary',title:'Primary source'}}]}}]}),{status:200});
};
await asOwner(A,async()=>{
 const job=await enqueueResearch({projectId:projectA,topic:'Account isolation evidence',instructions:'Primary sources',providerId:providerA});
 for(const expected of ['queued','queued','queued','completed'])assert.equal(await runSlice(A,job.jobId,job.generation),expected);
 assert.equal(calls,2);
 const source=await db.prepare('SELECT * FROM resources WHERE session_id=?').get(job.sessionId);assert.equal(source.status,'needs_approval');
 const finding=await db.prepare('SELECT * FROM findings WHERE session_id=?').get(job.sessionId);assert.deepEqual(JSON.parse(finding.source_urls_json),['https://example.org/primary']);
 const review=await db.prepare('SELECT * FROM resource_clarifications WHERE resource_id=?').get(source.id);await resolveApproval(review.id,'Security/References');assert.equal((await db.prepare('SELECT status FROM resources WHERE id=?').get(source.id)).status,'filed');
 ok('Native evidence and synthesis in separate invocations; verified URL filtering and resource approval');
 const continuation=await enqueueResearch({projectId:projectA,topic:'Account isolation evidence',instructions:'Primary sources',providerId:providerA,resumeSessionId:job.sessionId});
 assert.notEqual(continuation.sessionId,job.sessionId);assert.equal((await db.prepare('SELECT parent_session_id FROM sessions WHERE id=?').get(continuation.sessionId)).parent_session_id,job.sessionId);
 pause=true;assert.equal(await runSlice(A,continuation.jobId,continuation.generation),'paused');const before=calls;
 const resumed=await enqueueResearch({projectId:projectA,topic:'Account isolation evidence',instructions:'Primary sources',providerId:providerA,resumeSessionId:continuation.sessionId});
 assert.equal(await runSlice(A,continuation.jobId,continuation.generation),'stopped');
 for(const expected of ['queued','queued','completed'])assert.equal(await runSlice(A,resumed.jobId,resumed.generation),expected);
 assert.equal(calls,before+1);assert.equal((await db.prepare('SELECT count(*) AS n FROM findings WHERE title=?').get('Verified account isolation')).n,1);ok('Pause and resume reuse evidence, preserve history, reject stale workers, and suppress duplicates');
 repair=true;
 const repairJob=await enqueueResearch({projectId:projectA,topic:'JSON repair',instructions:'',providerId:providerA});const beforeRepair=calls;
 for(const expected of ['queued','queued','queued','queued','completed'])assert.equal(await runSlice(A,repairJob.jobId,repairJob.generation),expected);
 assert.equal(calls,beforeRepair+3);repair=false;ok('Invalid synthesis repaired once and saved before advancing');
 const interrupted=await enqueueResearch({projectId:projectA,topic:'Interrupted job',instructions:'',providerId:providerA});
 await db.prepare('UPDATE research_jobs SET updated_at=? WHERE id=?').run('2000-01-01T00:00:00.000Z',interrupted.jobId);await recoverInterruptedSessions();
 assert.equal((await db.prepare('SELECT status FROM sessions WHERE id=?').get(interrupted.sessionId)).status,'interrupted');
 assert.ok((await db.prepare('SELECT count(*) AS n FROM notifications WHERE session_id=?').get(interrupted.sessionId)).n>0);ok('Abandoned jobs become resumable and notify their owner');
 const atomic=await enqueueResearch({projectId:projectA,topic:'Atomic rollback',instructions:''});
 const n=(await db.prepare('SELECT count(*) AS n FROM findings').get()).n;
 await assert.rejects(()=>commitResearchResult(projectA,atomic.sessionId,{provider:'test',model:'test',sources:[],payload:{executiveSummary:'x',findings:[{title:'Rolled back',summary:'x',content:'x',recommendedFolderPath:'New',confidence:1,tags:[],sourceUrls:[],rationale:'x'},null],limitations:[],nextTasks:[],suggestedFolders:[]}} as any));
 assert.equal((await db.prepare('SELECT count(*) AS n FROM findings').get()).n,n);ok('Failed final save rolls back findings, folders, and logs together');
 await transaction(async()=>{for(let i=0;i<70;i++)await db.prepare('INSERT INTO decisions(id,project_id,rule_key,rule_value,reason,created_at) VALUES(?,?,?,?,?,?)').run(randomUUID(),projectA,'test','pagination fixture','pagination fixture',now());});
 const page=await searchKnowledge('pagination');assert.equal(page.results.length,30);assert.equal(page.total,70);assert.equal(page.nextOffset,30);assert.equal((await searchKnowledge('pagination','',60)).results.length,10);ok('Complete paginated search exceeds one screen of results');
});
await asOwner(B,async()=>{
 const p=(await getDashboardState()).projects[0].id;
 const bad=await saveProvider({presetId:'gemini',name:'Unavailable provider',model:'unavailable',apiKey:'redact-this-key'});
 const good=await saveProvider({presetId:'gemini',name:'Fallback provider',model:'fixture',apiKey:'second-fixture-key'});
 const original=globalThis.fetch;
 globalThis.fetch=async(url:any,init:any)=>String(url).includes('/unavailable:')?new Response(JSON.stringify({error:{message:'Key redact-this-key rejected'}}),{status:401}):original(url,init);
 const job=await enqueueResearch({projectId:p,topic:'Fallback resilience',instructions:'',providerId:'auto'});
 for(const status of ['queued','queued','queued','queued','completed'])assert.equal(await runSlice(B,job.jobId,job.generation),status);
 assert.equal((await getDashboardState()).limitations.some((l:any)=>l.code==='PROVIDER_FAILOVER_USED'),true);
 const state=JSON.stringify(await getDashboardState());assert.ok(!state.includes('redact-this-key'));
 assert.equal((await listProvidersPublic()).find(x=>x.id===good)?.status,'ready');
 ok('Automatic failover spans invocations, reports the switch, and redacts provider error credentials');
 globalThis.fetch=original;
});
await engine.exec('SET ROLE anon');await assert.rejects(()=>engine.query('SELECT * FROM atlas.projects'),/permission denied/);await engine.exec('RESET ROLE');ok('Anonymous database role has no Atlas access');
console.log(`\n${checks} cloud checks passed. No external database or AI key was used.`);
await engine.close();
